create table if not exists public.members (
  id bigint generated by default as identity primary key,
  name text not null unique,
  nickname text,
  is_archived boolean not null default false
);

create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  date date not null,
  minutes integer not null,
  comment text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists entries_member_id_idx on public.entries (member_id);
create index if not exists entries_date_idx on public.entries (date desc);

create table if not exists public.debts (
  id bigint generated by default as identity primary key,
  debtor_id bigint not null references public.members(id) on delete cascade,
  creditor_id bigint not null references public.members(id) on delete cascade,
  minutes integer not null,
  date date not null,
  comment text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists debts_debtor_idx on public.debts (debtor_id);
create index if not exists debts_creditor_idx on public.debts (creditor_id);
